version: '3.3'
services:
  post_db:
    container_name: dockermicroservices_mongo_db
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db

  ui:
    container_name: dockermicroservices_ui
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${EXT_PORT}:9292/tcp
    networks:
      - front_net
  post:
    container_name: dockermicroservices_post
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net

  comment:
    container_name: dockermicroservices_comment
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
